package com.example.ultimateguide.bot;

public enum BotState {
    START,
    WAITING_FOR_PHONE,
    MAIN_MENU,
    REGISTRATION,
    ACADEMIC_INFO,
    EXTRACURRICULAR_INFO,
    PERSONAL_INFO,
    VIEW_PROFILE,
    COLLEGE_RECOMMENDATIONS,
    ESSAY_HELPER,
    WAITING_FOR_SAT,
    WAITING_FOR_ACT,
    WAITING_FOR_IELTS,
    WAITING_FOR_GPA,
    WAITING_FOR_CLUB,
    WAITING_FOR_LEADERSHIP,
    WAITING_FOR_VOLUNTEER,
    WAITING_FOR_AWARD,
    WAITING_FOR_MAJOR,
    WAITING_FOR_COUNTRY,
    WAITING_FOR_FINANCIAL_STATE,
    WAITING_FOR_ESSAY
} 